services:
  - type: web
    name: mcq-exam-portal
    env: static
    buildCommand: npm install --production=false --force && npm run build
    staticPublishPath: mcq-exam-portal/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_FORCE
        value: true
      - key: NPM_CONFIG_AUDIT
        value: false
      - key: NPM_CONFIG_FUND
        value: false